# O QUE: Nome da nossa esteira de processos
name: Esteira de Validacao do Sistema

# QUANDO: Executar toda vez que houver um 'push' na branch main ou feature-*
on:
  push:
    branches: [ "main", "feature-*" ]
  pull_request:
    branches: [ "main" ]

# ONDE: As tarefas que ser√£o executadas
jobs:
  build-and-test:
    runs-on: ubuntu-latest  # FERRAMENTA: Usa um servidor Linux gratuito do GitHub

    steps:
      - name: Baixar o codigo do repositorio
        uses: actions/checkout@v3

      - name: Configurar o Python no servidor
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Validar se o Dockerfile consegue ser montado (Build)
        run: |
          docker build -t sistema-teste .
          echo "O AGENTE DIZ: O Build foi realizado com sucesso e o sistema e estavel!"